/* "uts46_status.h" */
/*
  generated by ucd.pl @ vmgentoo [Thu Aug 30 20:16:48 2012]
     - do not edit this file, edit ucd.pl instead -

*/
#pragma once
#ifndef __UTS46_STATUS_H__
#define __UTS46_STATUS_H__

/*
  Unicode IDNA Compatibility Processing
  see:
    http://unicode.org/reports/tr46/#IDNA_Mapping_Table

*/

#line 132 "../gen/inc/uts46_mapping.pl"
#define UTS46_mapping_maxlength 18

enum UTS46_STATUS
{
  uts46_status_Valid = 1 /* The code point is valid, and not modified. */,
  uts46_status_Ignored = 2 /* The code point is removed: this is equivalent to mapping the code point to an empty string. */,
  uts46_status_Mapped = 3 /* The code point is replaced in the string by the value for the mapping. */,
  uts46_status_Deviation = 4 /* The code point is either mapped or valid, depending on whether the processing is transitional or not. */,
  uts46_status_Disallowed = 5 /* The code point is not allowed. */,
  uts46_status_DisallowedSTD3Valid = 6 /* The status is disallowed if UseSTD3ASCIIRules=true, otherwise valid. */,
  uts46_status_DisallowedSTD3Mapped = 7 /* The status is disallowed if UseSTD3ASCIIRules=true, otherwise mapped. */
};





#endif
/* end of generated file */
